"""configure models cascade delete

Revision ID: 5ae34653793f
Revises: 94de7f1623b6
Create Date: 2025-08-07 16:13:27.099638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ae34653793f"
down_revision: Union[str, Sequence[str], None] = "94de7f1623b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(
        op.f("fk_cartitems_product_id_products"),
        "cartitems",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_cartitems_user_id_users"), "cartitems", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cartitems_product_id_products"),
        "cartitems",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_cartitems_user_id_users"),
        "cartitems",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "orderitems", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_orderitems_order_id_orders"), "orderitems", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_orderitems_order_id_orders"),
        "orderitems",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_orders_user_id_users"), "orders", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_orders_user_id_users"),
        "orders",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "products", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_products_category_id_categories"),
        "products",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_products_category_id_categories"),
        "products",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_category_id_categories"),
        "products",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_products_category_id_categories"),
        "products",
        "categories",
        ["category_id"],
        ["id"],
    )
    op.alter_column(
        "products", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("fk_orders_user_id_users"), "orders", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_orders_user_id_users"), "orders", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(
        op.f("fk_orderitems_order_id_orders"), "orderitems", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_orderitems_order_id_orders"),
        "orderitems",
        "orders",
        ["order_id"],
        ["id"],
    )
    op.alter_column(
        "orderitems", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("fk_cartitems_user_id_users"), "cartitems", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_cartitems_product_id_products"),
        "cartitems",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_cartitems_user_id_users"),
        "cartitems",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_cartitems_product_id_products"),
        "cartitems",
        "products",
        ["product_id"],
        ["id"],
    )
